### ISSUE TITLE
Reset give NaN

### ISSUE THREAD

**Issue by fharper** [yo7/pomojo#4]
When you start a pomodoro, stop it and reset it, I get a NaN:NaN as time. I need to restart the app to get back numbers.

![image](https://user-images.githubusercontent.com/1170989/62567872-16c3aa00-b85a-11e9-8875-35cb5bba28f3.png)

**Comment by fharper** [comment]
It also happen after one pomodoro + break.

**Comment by yo7** [comment]
Sorry about that but I'm not using the app myself😓 If you need to fix that please fork
